# Default values for go-gist-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: gist-api-go
  image:
    name: gist-api-go
    tag: "latest"
  replicas: 2

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8080
  nodeport: 30080