name: ci

on:
  push:
    branches: main

jobs:
  build:
    environment: production
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6

      #- uses: actions/setup-go@v6
      #  with:
      #    go-version: ${{ vars.GO_VERSION }}

      #- name: Test this code before building
      #  run: go test ./...  && echo "Test case if success"; exit 0 || ( echo "Test cases failed..."; exit 1)
      
      - name: docker login
        run: docker login ${{ vars.HARBOR_IP }} -u '${{ vars.HARBOR_ROBOT_USER }}' -p ${{ secrets.HARBOR_SECRET }}

      - name: HELM login
        run: helm registry login ${{ vars.HARBOR_IP }} -u '${{ vars.HARBOR_ROBOT_USER }}' -p ${{ secrets.HARBOR_SECRET }} --plain-http
      

      - name: Set env
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c 1-6)
          VERSION=$(grep 'APP_VERSION' mainfest.mf | cut -d '=' -f2 | tr -d ' ')
          echo "IMAGE_TAG=${VERSION}-${SHORT_SHA}" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT=${SHORT_SHA}" >> $GITHUB_ENV
          echo "APP_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: docker build & push
        run: docker build --build-arg VERSION=${{ env.APP_VERSION }} --build-arg GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }} -t ${{ vars.HARBOR_IP }}/production/go-app:${{ env.IMAGE_TAG }} .